### ISSUE TITLE
Проблемы с зеркалами загрузки

### ISSUE THREAD

**Issue by Dev-Cored** [evgvs/turboarch#3]
Приветствую! Попытался перейти на Arch с Debian 12. Возникла проблема с зеркалами. Прикрепляю ошибку:

`Downloading archlinux-bootstrap
--2024-05-03 18:45:17--  https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.gz
Распознаётся geo.mirror.pkgbuild.com (geo.mirror.pkgbuild.com)… 89.187.191.12, 2a02:6ea0:c237::2
Подключение к geo.mirror.pkgbuild.com (geo.mirror.pkgbuild.com)|89.187.191.12|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 404 Not Found
2024-05-03 18:45:17 ОШИБКА 404: Not Found.
`
Идея проекта реально интересная, жалко что возникли ошибки!

**Comment by Dev-Cored** [comment]
Так же пробовал запуск с текущими и лучшими зеркалами, все точно такая же ошибка

**Comment by evgvs** [comment]
now it is not archlinux-bootstrap-x86_64.**tar.gz**, it is archlinux-bootstrap-x86_64.**tar.zst**. fixed in the last commit.

**Comment by Dev-Cored** [comment]
Спасибо! Все заработало!
