### ISSUE TITLE
Добавить файл с лицензией

### ISSUE THREAD

**Issue by lotigara** [evgvs/turboarch#7]
Просто для подтверждения того, что эта программа свободна. А то вдруг все форки не на GitHub (GitLab, Forgejo, ...) нелегальны ;-)

Например, [Expat](https://directory.fsf.org/wiki/License:Expat), [Apache 2.0](https://directory.fsf.org/wiki/License:Apache-2.0) или [GPL 3.0](https://directory.fsf.org/wiki/License:GPL-3.0-or-later).

По теме: https://docs.github.com/ru/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

**Comment by evgvs** [comment]
мне похуй 😂😂😂

**Comment by lotigara** [comment]
...
